# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/thmste021/EEE4120F/EEE4120F/Prac4/ug937-design-files/practical_4/practical_4.srcs/sources_1/ip/sine_mid/sine_mid.xci
# IP: The module: 'sine_mid' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/thmste021/EEE4120F/EEE4120F/Prac4/ug937-design-files/practical_4/practical_4.gen/sources_1/ip/sine_mid/sine_mid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_mid'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/thmste021/EEE4120F/EEE4120F/Prac4/ug937-design-files/practical_4/practical_4.srcs/sources_1/ip/sine_mid/sine_mid.xci
# IP: The module: 'sine_mid' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/thmste021/EEE4120F/EEE4120F/Prac4/ug937-design-files/practical_4/practical_4.gen/sources_1/ip/sine_mid/sine_mid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_mid'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
